[package]
name = "forge-store"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Crabforge read models in gres"

[lints]
workspace = true

[dependencies]
forge-types.workspace = true
refinement-types.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
tracing.workspace = true

[dev-dependencies]
assert2.workspace = true
forge-testkit.workspace = true
