[package]
name = "forge-server"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "The Crabforge server"

[lints]
workspace = true

[[bin]]
name = "crabforge-server"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
argon2.workspace = true
getrandom.workspace = true
axum.workspace = true
clap.workspace = true
crabka-client-admin.workspace = true
forge-bus.workspace = true
forge-command.workspace = true
forge-git.workspace = true
forge-githttp.workspace = true
forge-projector.workspace = true
forge-store.workspace = true
forge-types.workspace = true
forge-topics.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
assert2.workspace = true
forge-testkit.workspace = true
tower.workspace = true
